apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ballandbeer

resources:
- ../../base
- argocd-vars.yaml

labels:
- includeSelectors: true
  pairs:
    environment: dev
    app.kubernetes.io/managed-by: argocd

patches:
- target:
    kind: Deployment
    name: recommender
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: hao1706/recommender:latest
    - op: replace
      path: /spec/template/spec/containers/0/env
      value:
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: recommender-vars
              key: S3_BUCKET_NAME
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: recommender-vars
              key: AWS_REGION
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: recommender-vars
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: recommender-vars
              key: LOG_LEVEL

- target:
    kind: ServiceAccount
    name: recommender-sa
  patch: |-
    - op: replace
      path: /metadata/annotations/eks.amazonaws.com~1role-arn
      value: arn:aws:iam::259959202589:role/ballandbeer-dev-eks-recommender-role

configMapGenerator:
- name: recommender-config
  behavior: create
  literals:
  - ENVIRONMENT=dev
  - LOG_LEVEL=debug