apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-api
spec:
  template:
    spec:
      containers:
        - name: recommender-api
          image: hao1706/ballandbeer:recommender
