apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ballandbeer

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: collector
  app.kubernetes.io/component: metrics-collector
  app.kubernetes.io/part-of: ballandbeer
