apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    app: collector
spec:
  type: ClusterIP
  selector:
    app: collector
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
