pipeline{
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage('Checkout SCM') {
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/test_lab']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/haihhdev/ballandbeer.git']])
                }
            }
        }
        stage('Initializing Terraform'){
            steps {
                script {
                    dir('ops/tf-aws-eks'){
                        sh 'terraform init'
                    }
                }
            }
        }
        stage('Validating Terraform'){
            steps {
                script {
                    dir('ops/tf-aws-eks'){
                        sh 'terraform validate'
                    }
                }
            }
        }
        stage('Terraform Plan'){
            steps {
                script {
                    dir('ops/tf-aws-eks'){
                        sh 'terraform plan -var-file=variables/dev.tfvars'
                    }
                }
            }
        }
        stage('Creating/Destroying EKS Cluster'){
            steps {
                script {
                    dir('ops/tf-aws-eks'){
                        sh 'terraform $action -var-file=variables/dev.tfvars -auto-approve' 
                    }
                }
            }
        }
        stage('Deploying BallandBeer to EKS') {
            steps {
                script {
                    sh 'aws eks update-kubeconfig --name EKS-Cluster-ballandbeer'
                    sh 'kubectl get namespace ballandbeer || kubectl create namespace ballandbeer'
                    def services = ['frontend', 'authen', 'booking', 'order', 'product', 'profile']
                    for (svc in services) {
                        sh "kubectl apply -f k8s/${svc}/"
                    }
                    sh 'kubectl apply -f k8s/ingress.yaml'
                }
            }
        }
    }
}