apiVersion: batch/v1
kind: Job
metadata:
  name: k6-weekday-job
  namespace: ballandbeer
spec:
  backoffLimit: 0 # Do not retry on failure, as K6 tests are long-running
  template:
    metadata:
      labels:
        app: k6-weekday
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      restartPolicy: Never
      priorityClassName: k6-high-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - collector
              topologyKey: kubernetes.io/hostname
      containers:
      - name: k6
        image: grafana/k6:latest
        command:
          - k6
          - run
          - --env
          - BASE_URL=
          - /scripts/weekday-traffic.js
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: k6-script
          mountPath: /scripts
      volumes:
      - name: k6-script
        configMap:
          name: k6-weekday-script

