apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: hao1706/profile:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"