apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: profile
        image: hao1706/ballandbeer:profile
        imagePullPolicy: Always
        ports:
        - containerPort: 4004