apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  labels:
    app: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          command: ["redpanda"]
          args:
            - start
            - --kafka-addr=internal://0.0.0.0:9092
            - --advertise-kafka-addr=internal://redpanda.default.svc.cluster.local:9092
            - --rpc-addr=redpanda.default.svc.cluster.local:33145
            - --advertise-rpc-addr=redpanda.default.svc.cluster.local:33145
            - --mode=dev-container
            - --smp=1
            - --default-log-level=info
          ports:
            - containerPort: 9092
            - containerPort: 9644
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
