apiVersion: v1
kind: Service
metadata:
  name: recommender-api
spec:
  selector:
    app: recommender-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4005
  type: ClusterIP
